export const CREATE_ROTA = 'CREATE_ROTA';
export const FETCH_ROTA = 'FETCH_ROTA';
export const FETCH_ROTAS = 'FETCH_ROTAS';
export const FETCH_HARD_RULES = 'FETCH_HARD_RULES';
export const FETCH_SOFT_RULES = 'FETCH_SOFT_RULES';